name: diabetes_ml_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # Pilih versi Python yang stabil dan kompatibel dengan MLflow
  - pip
  - pip:
    # Pustaka utama
    - pandas
    - scikit-learn
    - numpy
    - joblib
    # Pustaka untuk MLflow
    - mlflow>=2.12.2  # Versi terbaru untuk kompatibilitas Python 3.10/3.12
    # Pustaka tambahan yang diperlukan
    - matplotlib
    - pyyaml